server:
  port: 8081

spring:
  application:
    name: link-shortener
  datasource:
    url: jdbc:postgresql://localhost:5432/shortener
    username: dev
    password: Ab123456
    hikari:
      schema: link_shortener
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema};
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml

link-shortener:
  system-id: ${spring.application.name}
  short-link-length: 12
